### ISSUE TITLE
Eingabe speichert "0" statt NULL

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_decimal#11]
SQL-Standard-Wert ist aber NULL

siehe auch https://github.com/MetaModels/attribute_numeric/issues/8

![shot134](https://cloud.githubusercontent.com/assets/1045318/13365324/a70a9782-dcd4-11e5-9453-da8c0d766a09.jpg)

**Comment by discordier** [comment]
Yeah, but you specify a 0 which will get saved

**Comment by xantippe** [comment]
ich habe das Feld "Dezimal" nicht ausgefüllt - also "nichts" eingegeben... an welcher Stelle habe ich definiert, dass stattdessen eine "0" gespeichert werden soll?

**Comment by xantippe** [comment]
@all: zur Info: Die "Null" kommt von Contao und kann durch MM nicht umgangen werden - eine Anpassung an der Stelle soll es in Contao 5.x - ggf. schon ab 4.2 - geben.

Bis dahin schließe ich das Ticket.

Dank an @discordier an die Aufklärung!

**Comment by zonky2** [comment]
ich mach das mal wieder auf und "Future"

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/attribute_decimal/pull/16
