### ISSUE TITLE
Empty string will be saved as "0" in database

### ISSUE THREAD

**Issue by richardhj** [MetaModels/attribute_decimal#13]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_decimal/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.0      |                                  |
| Contao version:                     |      3.5.21    |                                  |
| MetaModels version:                 |   hotfix15       |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |      all    |                                  |

## Issue description

When the attribute value is an empty string (''), it will be saved as "0" in the database. Expected behavior would be saving `null`.

## Steps to reproduce

```php
/** @var \MetaModels\IItem $item */
$item->set('decimal-attr', '');
$item->save();
```

This could be added to the attribute class.
```php
    public function setDataFor($arrValues)
    {
        // Translate all '' values to null, so they will not set as `0` in the database.
        $arrValues = array_map(function ($value) {
            return '' === $value ? null : $value;
        }, $arrValues);

        parent::setDataFor($arrValues);
    }
```

I'm not sure, whether this is a issue, because this does not happen when using the dcg (in the back end).
When this issue will be confirmed, I could provide a PR.

Same for `attribute_numeric`.

**Comment by richardhj** [comment]
I do not set an empty string on my self - I'm validating a form (like `\Input::post('decimal-attr')`) which returns an empty string when the user did no input.

**Comment by zonky2** [comment]
may be ... we can talk about the "best strategy" at next MM-call...

**Comment by richardhj** [comment]
Needs further debugging corresponding to the back end input mask too.

**Comment by zonky2** [comment]
@richardhj you got that on the "radar"?

**Comment by zonky2** [comment]
relatet to strict mode bugs - see https://github.com/MetaModels/core/issues/1232
