### ISSUE TITLE
mandatory decimal Asterisk (*) and errormessage missing

### ISSUE THREAD

**Issue by asaage** [MetaModels/attribute_decimal#8]
when declared as mandatory in the input-mask the Asterisk is missing.
On submission you will get no error-message - instead it fills in a "0" silently.

**Comment by xantippe** [comment]
aktueller Test unter core 2.0.0-alpha8 und attribute_decimal 	2.0.0-alpha2

* Eingabe Text wird abgefangen
* Eingabe 213,3456 wird zu 213.3456
* **Keine Eingabe wird nicht abgefangen**

**Comment by xantippe** [comment]
PR zum Test erstellt https://github.com/MetaModels/attribute_decimal/pull/9

**Comment by xantippe** [comment]
siehe auch https://github.com/MetaModels/core/issues/957

**Comment by discordier** [comment]
Should be fixed with alpha3

**Comment by xantippe** [comment]
getestet mit  	metamodels/attribute_decimal 	dev-develop (126f8194)

![shot85](https://cloud.githubusercontent.com/assets/1045318/12609350/7cc8049c-c4e1-11e5-89b2-6f34ef7300f1.jpg)

**Comment by discordier** [comment]
Confirmed as fixed by @xantippe

**Comment by asaage** [comment]
@xantippe wie sieht's aus wenn es nicht mandatory ist - wird dann beim speichern immernoch eine ```0``` eigesetzt? Sorry ich habe gerade keine Möglichkeit das zu testen.

**Comment by xantippe** [comment]
welcher Wert gespeichert wird hat mit dem Mandantory nix zu tun

**Comment by xantippe** [comment]
@asaage zur Info: es wird immer noch "0" statt NULL gespeichert

https://github.com/MetaModels/attribute_decimal/issues/11
